#!/usr/bin/env python3
"""
Plot the empirical CDF of the overall episode-wise minimum TTC.

For each evaluated method, the script expects a safety_margin_metrics.npz file
generated by the evaluation script. For each episode, it computes

    overall_episode_min_ttc =
        min(
            episode_min_ttc_current_front,
            episode_min_ttc_target_front,
            episode_min_ttc_target_rear
        )

and plots the empirical CDF of this quantity.

By default, only finite TTC values are plotted. Episodes whose overall minimum
TTC is +inf (i.e., no closing conflict with any of the three interaction
partners during the episode) are excluded from the plotted CDF and reported in
the console output.

Example:
    python plot_overall_min_ttc_cdf.py \
        --inputs sacd/safety_margin_metrics.npz \
                 ppo/safety_margin_metrics.npz \
                 idm/safety_margin_metrics.npz \
        --labels SACD PPO "IDM+MOBIL" \
        --output overall_min_ttc_cdf.png

Optional:
    --ttc-threshold 1.5
    --x-max 10.0
    --title "Overall episode-wise minimum TTC"
    --show
"""

import argparse
import os
import numpy as np
import matplotlib.pyplot as plt


def parse_args():
    parser = argparse.ArgumentParser(
        description="Plot the CDF of the overall episode-wise minimum TTC."
    )
    parser.add_argument(
        "--inputs",
        nargs="+",
        required=True,
        help="One or more safety_margin_metrics.npz files.",
    )
    parser.add_argument(
        "--labels",
        nargs="+",
        required=True,
        help="Labels corresponding to the input NPZ files.",
    )
    parser.add_argument(
        "--output",
        type=str,
        default="overall_min_ttc_cdf.png",
        help="Output image path (default: overall_min_ttc_cdf.png).",
    )
    parser.add_argument(
        "--ttc-threshold",
        type=float,
        default=1.5,
        help="Critical TTC threshold to show as a vertical reference line (default: 1.5).",
    )
    parser.add_argument(
        "--x-max",
        type=float,
        default=None,
        help="Optional maximum x-axis value in seconds.",
    )
    parser.add_argument(
        "--title",
        type=str,
        default="Overall episode-wise minimum TTC",
        help="Plot title.",
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Display the plot interactively in addition to saving it.",
    )
    return parser.parse_args()


def load_overall_episode_min_ttc(npz_path):
    data = np.load(npz_path)

    required_keys = [
        "episode_min_ttc_current_front",
        "episode_min_ttc_target_front",
        "episode_min_ttc_target_rear",
    ]
    missing = [key for key in required_keys if key not in data]
    if missing:
        raise KeyError(
            f"{npz_path} is missing required keys: {', '.join(missing)}"
        )

    current_front = np.asarray(data["episode_min_ttc_current_front"], dtype=float)
    target_front = np.asarray(data["episode_min_ttc_target_front"], dtype=float)
    target_rear = np.asarray(data["episode_min_ttc_target_rear"], dtype=float)

    if not (
        current_front.shape == target_front.shape == target_rear.shape
    ):
        raise ValueError(
            f"Episode TTC arrays in {npz_path} do not have matching shapes."
        )

    overall_min = np.minimum.reduce([current_front, target_front, target_rear])
    return overall_min


def empirical_cdf(values):
    """Return sorted finite values and their empirical CDF."""
    values = np.asarray(values, dtype=float)
    values = values[np.isfinite(values)]
    values = np.sort(values)

    if values.size == 0:
        return values, values

    y = np.arange(1, values.size + 1) / values.size
    return values, y


def main():
    args = parse_args()

    if len(args.inputs) != len(args.labels):
        raise ValueError("The number of --inputs and --labels must match.")

    plt.figure(figsize=(6.0, 4.0))

    any_curve = False

    for npz_path, label in zip(args.inputs, args.labels):
        overall_min = load_overall_episode_min_ttc(npz_path)

        finite_mask = np.isfinite(overall_min)
        finite_values = overall_min[finite_mask]
        num_total = overall_min.size
        num_finite = finite_values.size
        num_infinite = int(np.isinf(overall_min).sum())
        num_nan = int(np.isnan(overall_min).sum())

        print(f"\n{label}")
        print("-" * len(label))
        print(f"File: {npz_path}")
        print(f"Total episodes: {num_total}")
        print(f"Finite overall min TTC episodes: {num_finite}")
        print(f"Infinite overall min TTC episodes: {num_infinite}")
        print(f"NaN overall min TTC episodes: {num_nan}")

        if num_finite == 0:
            print("No finite TTC values available; skipping this method.")
            continue

        x, y = empirical_cdf(finite_values)
        #legend_label = f"{label} (n={num_finite})"
        legend_label = f"{label}"
        plt.step(x, y, where="post", label=legend_label)
        any_curve = True

    if not any_curve:
        raise RuntimeError("No finite TTC data available to plot.")

    if args.ttc_threshold is not None:
        plt.axvline(
            x=args.ttc_threshold,
            linestyle="--",
            linewidth=1.2,
            alpha=0.9,
            #label=fr"TTC threshold ({args.ttc_threshold:g} s)",
            label=fr"TTC threshold",
        )

    plt.xlabel("Overall episode-wise minimum TTC [s]")
    plt.ylabel("Empirical CDF")
    plt.title(args.title)
    plt.ylim(0.0, 1.0)

    if args.x_max is not None:
        plt.xlim(0.0, args.x_max)
    else:
        plt.xlim(left=0.0)

    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()

    output_dir = os.path.dirname(args.output)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    plt.savefig(args.output, dpi=300, bbox_inches="tight")
    print(f"\nSaved plot to: {args.output}")

    if args.show:
        plt.show()
    else:
        plt.close()


if __name__ == "__main__":
    main()
